enum AnimationEnum {
  static(name: "Static", animationId: 0),
  blink(name: "Blink", animationId: 1),
  breath(name: "Atmen", animationId: 2),
  color_wipe(name: "Color Wipe", animationId: 3),
  color_wipe_inv(name: "Color Wipe Inv", animationId: 4),
  color_wipe_rev(name: "Color Wipe Rev", animationId: 5),
  color_wipe_rev_inv(name: "Color Wipe Rev Inv", animationId: 6),
  color_wipe_random(name: "Color Wipe zufällig", animationId: 7),
  random_color(name: "Farbe zufällig", animationId: 8),
  single_dynamic(name: "Einzeln Dynamisch", animationId: 9),
  multi_dynamic(name: "Multi Dynamisch", animationId: 10),
  rainbow(name: "Regenbogen", animationId: 11),
  rainbow_cycle(name: "Regenbogen Kreis", animationId: 12),
  scan(name: "Scan", animationId: 13),
  dual_scan(name: "Dualer Scan", animationId: 14),
  fade(name: "Fade", animationId: 15),
  theater_chase(name: "Theater", animationId: 16),
  theater_chase_rainbow(name: "Theater Regenbogen", animationId: 17),
  running_lights(name: "Laufend", animationId: 18),
  twinkle(name: "Sternchen", animationId: 19),
  twinkle_random(name: "Sternchen zufällig", animationId: 20),
  twinkle_fade(name: "Sternchen Fade", animationId: 21),
  twinkle_fade_random(name: "Sternchen Fade zufällig", animationId: 22),
  sparkle(name: "Funkeln", animationId: 23),
  flash_sparkle(name: "Funkekln Flash", animationId: 24),
  hyper_sparkle(name: "Hyper Funkeln", animationId: 25),
  strobe(name: "Stroboskop", animationId: 26),
  strobe_rainbow(name: "Stroboskop Regenbogen", animationId: 27),
  multi_strobe(name: "Multi-Stroboskop", animationId: 28),
  blink_rainbow(name: "Regenboben blinken", animationId: 29),
  chase_white(name: "Weiß", animationId: 30),
  chase_color(name: "Farbe", animationId: 31),
  chase_random(name: "Zufall", animationId: 32),
  chase_rainbow(name: "Regenbogen", animationId: 33),
  chase_flash(name: "Flash", animationId: 34),
  chase_flash_random(name: "Flash Zufall", animationId: 35),
  chase_rainbow_white(name: "Weißer Regenbogen", animationId: 36),
  chase_blackout(name: "Schwarz ausgehend", animationId: 37),
  chase_blackout_rainbow(name: "Regenbogen ausgehend", animationId: 38),
  color_sweep_random(name: "Wischen zufällig", animationId: 39),
  running_color(name: "Laufende Farbe", animationId: 40),
  running_red_blue(name: "Rot-Blau laufend", animationId: 41),
  running_random(name: "Zufällig laufend", animationId: 42),
  larson_scanner(name: "Scanner", animationId: 43),
  comet(name: "Komet", animationId: 44),
  fireworks(name: "Feuerwerk", animationId: 45),
  fireworks_random(name: "Feuerwerk zufällig", animationId: 46),
  merry_christmas(name: "Weihnachten", animationId: 47),
  fire_flicker(name: "Feuer", animationId: 48),
  fire_flicker_soft(name: "Leichtes Feuer", animationId: 49),
  fire_flicker_intense(name: "Intensives Feuer", animationId: 50),
  circus_combustus(name: "Zirkus", animationId: 51),
  halloween(name: "Halloween", animationId: 52),
  bicolor_chase(name: "BICOLOR", animationId: 53),
  tricolor_chase(name: "TRICOLOR", animationId: 54),
  twinklefox(name: "TWINKLEFOX", animationId: 55),
  rain(name: "Regen", animationId: 56);
  
  const AnimationEnum({required this.name, required this.animationId});

  final String name;
  final int animationId;
}